CREATE TABLE IF NOT EXISTS `base_geo_country` (
`id` int(3) NOT NULL,
  `name` varchar(50) NOT NULL,
  `country` varchar(7) NOT NULL
) ENGINE=MyISAM AUTO_INCREMENT=252 DEFAULT CHARSET=utf8;
<next>
ALTER TABLE `base_geo_country`
 ADD PRIMARY KEY (`id`);
<next>
INSERT INTO `base_geo_country` (`id`, `name`, `country`) VALUES
(1, '0', '0'),
(2, 'Australia', 'AU'),
(3, 'China', 'CN'),
(4, 'Japan', 'JP'),
(5, 'Thailand', 'TH'),
(6, 'United States', 'US'),
(7, 'India', 'IN'),
(8, 'Malaysia', 'MY'),
(9, 'Korea, Republic of', 'KR'),
(10, 'Singapore', 'SG'),
(11, 'Hong Kong', 'HK'),
(12, 'Taiwan, Province of China', 'TW'),
(13, 'Philippines', 'PH'),
(14, 'Vietnam', 'VN'),
(15, 'United Kingdom', 'GB'),
(16, 'France', 'FR'),
(17, 'European Union', 'EU'),
(18, 'Germany', 'DE'),
(19, 'Israel', 'IL'),
(20, 'Sweden', 'SE'),
(21, 'Italy', 'IT'),
(22, 'Netherlands', 'NL'),
(23, 'Greece', 'GR'),
(24, 'Spain', 'ES'),
(25, 'Austria', 'AT'),
(26, 'Belgium', 'BE'),
(27, 'United Arab Emirates', 'AE'),
(28, 'Russian Federation', 'RU'),
(29, '', 'A1'),
(30, 'Kazakhstan', 'KZ'),
(31, 'Portugal', 'PT'),
(32, 'Saudi Arabia', 'SA'),
(33, 'Denmark', 'DK'),
(34, 'Iran, Islamic Republic of', 'IR'),
(35, 'Norway', 'NO'),
(36, 'Canada', 'CA'),
(37, 'Mexico', 'MX'),
(38, 'Ireland', 'IE'),
(39, 'Syrian Arab Republic', 'SY'),
(40, 'Ukraine', 'UA'),
(41, 'Cyprus', 'CY'),
(42, 'Czech Republic', 'CZ'),
(43, 'Switzerland', 'CH'),
(44, 'Iraq', 'IQ'),
(45, 'Turkey', 'TR'),
(46, 'Romania', 'RO'),
(47, 'Lebanon', 'LB'),
(48, 'Georgia', 'GE'),
(49, 'Brazil', 'BR'),
(50, 'Azerbaijan', 'AZ'),
(51, 'Zimbabwe', 'ZW'),
(52, 'South Africa', 'ZA'),
(53, '', 'A2'),
(54, 'Palestinian Territory, Occupied', 'PS'),
(55, 'Lithuania', 'LT'),
(56, 'Oman', 'OM'),
(57, 'Slovakia', 'SK'),
(58, 'Serbia', 'RS'),
(59, 'Finland', 'FI'),
(60, 'Iceland', 'IS'),
(61, 'Hungary', 'HU'),
(62, 'Moldova', 'MD'),
(63, 'Bulgaria', 'BG'),
(64, 'Slovenia', 'SI'),
(65, 'Macedonia, The Former Yugoslav Republic Of', 'MK'),
(66, 'Angola', 'AO'),
(67, 'Liechtenstein', 'LI'),
(68, 'Jersey', 'JE'),
(69, 'Poland', 'PL'),
(70, 'Croatia', 'HR'),
(71, 'Bosnia and Herzegovina', 'BA'),
(72, 'Estonia', 'EE'),
(73, 'Latvia', 'LV'),
(74, 'Jordan', 'JO'),
(75, 'Kyrgyzstan', 'KG'),
(76, 'Reunion', 'RE'),
(77, 'Mayotte', 'YT'),
(78, 'Isle of Man', 'IM'),
(79, 'Libyan Arab Jamahiriya', 'LY'),
(80, 'Luxembourg', 'LU'),
(81, 'Armenia', 'AM'),
(82, 'Virgin Islands, British', 'VG'),
(83, 'Yemen', 'YE'),
(84, 'Belarus', 'BY'),
(85, 'Guadeloupe', 'GP'),
(86, 'Gibraltar', 'GI'),
(87, 'Kenya', 'KE'),
(88, 'Bolivia, plurinational state of', 'BO'),
(89, 'Chile', 'CL'),
(90, 'Qatar', 'QA'),
(91, 'Kuwait', 'KW'),
(92, 'Martinique', 'MQ'),
(93, 'French Guiana', 'GF'),
(94, 'Puerto Rico', 'PR'),
(95, 'Indonesia', 'ID'),
(96, 'Guam', 'GU'),
(97, 'Dominican Republic', 'DO'),
(98, 'Virgin Islands, U.S.', 'VI'),
(99, 'Pakistan', 'PK'),
(100, 'Mongolia', 'MN'),
(101, 'New Zealand', 'NZ'),
(102, 'Nepal', 'NP'),
(103, 'Papua New Guinea', 'PG'),
(104, '', 'AP'),
(105, 'Panama', 'PA'),
(106, 'Costa Rica', 'CR'),
(107, 'Peru', 'PE'),
(108, 'Belize', 'BZ'),
(109, 'Nigeria', 'NG'),
(110, 'Venezuela', 'VE'),
(111, 'Bahamas', 'BS'),
(112, 'Morocco', 'MA'),
(113, 'Colombia', 'CO'),
(114, 'Seychelles', 'SC'),
(115, 'Barbados', 'BB'),
(116, 'Egypt', 'EG'),
(117, 'Brunei Darussalam', 'BN'),
(118, 'Bahrain', 'BH'),
(119, 'Aruba', 'AW'),
(120, 'Saint Lucia', 'LC'),
(121, 'Argentina', 'AR'),
(122, 'Bangladesh', 'BD'),
(123, 'Tokelau', 'TK'),
(124, 'Cambodia', 'KH'),
(125, 'Macao', 'MO'),
(126, 'Maldives', 'MV'),
(127, 'Afghanistan', 'AF'),
(128, 'New Caledonia', 'NC'),
(129, 'Fiji', 'FJ'),
(130, 'Wallis and Futuna', 'WF'),
(131, 'Albania', 'AL'),
(132, 'Uzbekistan', 'UZ'),
(133, 'Montenegro', 'ME'),
(134, 'Congo, Democratic Republic of the', 'CD'),
(135, 'Korea, Democratic People''s republic of', 'KP'),
(136, 'Holy See (Vatican City State)', 'VA'),
(137, 'Antarctica', 'AQ'),
(138, 'Bermuda', 'BM'),
(139, 'Curaçao', 'CW'),
(140, 'Ecuador', 'EC'),
(141, 'Saint Kitts and Nevis', 'KN'),
(142, 'Samoa', 'WS'),
(143, 'Guernsey', 'GG'),
(144, 'Malta', 'MT'),
(145, 'Tajikistan', 'TJ'),
(146, 'Liberia', 'LR'),
(147, 'Ghana', 'GH'),
(148, 'Tanzania, United Republic Of', 'TZ'),
(149, 'Zambia', 'ZM'),
(150, 'Madagascar', 'MG'),
(151, 'Namibia', 'NA'),
(152, 'Cote d''Ivoire', 'CI'),
(153, 'Sudan', 'SD'),
(154, 'Uganda', 'UG'),
(155, 'Cameroon', 'CM'),
(156, 'Malawi', 'MW'),
(157, 'Gabon', 'GA'),
(158, 'Mali', 'ML'),
(159, 'Benin', 'BJ'),
(160, 'Chad', 'TD'),
(161, 'Botswana', 'BW'),
(162, 'Cape Verde', 'CV'),
(163, 'Rwanda', 'RW'),
(164, 'Congo', 'CG'),
(165, 'Mozambique', 'MZ'),
(166, 'Gambia', 'GM'),
(167, 'Lesotho', 'LS'),
(168, 'Mauritius', 'MU'),
(169, 'Algeria', 'DZ'),
(170, 'Guinea', 'GN'),
(171, 'Swaziland', 'SZ'),
(172, 'Burkina Faso', 'BF'),
(173, 'Sierra Leone', 'SL'),
(174, 'Somalia', 'SO'),
(175, 'Niger', 'NE'),
(176, 'Central African Republic', 'CF'),
(177, 'Togo', 'TG'),
(178, 'Burundi', 'BI'),
(179, 'Equatorial Guinea', 'GQ'),
(180, 'South Sudan', 'SS'),
(181, 'Senegal', 'SN'),
(182, 'Mauritania', 'MR'),
(183, 'Djibouti', 'DJ'),
(184, 'Comoros', 'KM'),
(185, 'Tunisia', 'TN'),
(186, 'Vanuatu', 'VU'),
(187, 'Bhutan', 'BT'),
(188, 'Myanmar', 'MM'),
(189, 'Micronesia, Federated States of', 'FM'),
(190, 'French Polynesia', 'PF'),
(191, 'Sri Lanka', 'LK'),
(192, 'Lao People''s Democratic Republic', 'LA'),
(193, 'Timor-Leste', 'TL'),
(194, 'Tonga', 'TO'),
(195, 'Greenland', 'GL'),
(196, 'Cayman Islands', 'KY'),
(197, 'Jamaica', 'JM'),
(198, 'Guatemala', 'GT'),
(199, 'Marshall Islands', 'MH'),
(200, 'Monaco', 'MC'),
(201, 'Anguilla', 'AI'),
(202, 'Grenada', 'GD'),
(203, 'Paraguay', 'PY'),
(204, 'Montserrat', 'MS'),
(205, 'Turks and Caicos Islands', 'TC'),
(206, 'Antigua and Barbuda', 'AG'),
(207, 'Tuvalu', 'TV'),
(208, 'Solomon Islands', 'SB'),
(209, 'Suriname', 'SR'),
(210, 'Cook Islands', 'CK'),
(211, 'Niue', 'NU'),
(212, 'French Southern Territories', 'TF'),
(213, 'Norfolk Island', 'NF'),
(214, 'Turkmenistan', 'TM'),
(215, 'Pitcairn', 'PN'),
(216, 'San Marino', 'SM'),
(217, 'Aland Islands', 'AX'),
(218, 'Faroe Islands', 'FO'),
(219, 'Svalbard and Jan Mayen', 'SJ'),
(220, 'Cocos (Keeling) Islands', 'CC'),
(221, 'Nauru', 'NR'),
(222, 'South Georgia and the South Sandwich Islands', 'GS'),
(223, 'United States Minor Outlying Islands', 'UM'),
(224, 'Sint Maarten', 'SX'),
(225, 'Guinea-Bissau', 'GW'),
(226, 'Saint Martin (French Part)', 'MF'),
(227, 'Saint Vincent and the Grenadines', 'VC'),
(228, 'Saint Pierre and Miquelon', 'PM'),
(229, 'Saint Barthélemy', 'BL'),
(230, 'Dominica', 'DM'),
(231, 'Sao Tome and Principe', 'ST'),
(232, 'Falkland Islands (Malvinas)', 'FK'),
(233, 'Northern Mariana Islands', 'MP'),
(234, 'Bonaire, Sint Eustatius and Saba', 'BQ'),
(235, 'Kiribati', 'KI'),
(236, 'Palau', 'PW'),
(237, 'Guyana', 'GY'),
(238, 'Honduras', 'HN'),
(239, 'Nicaragua', 'NI'),
(240, 'El Salvador', 'SV'),
(241, 'Andorra', 'AD'),
(242, 'Haiti', 'HT'),
(243, 'Trinidad and Tobago', 'TT'),
(244, 'American Samoa', 'AS'),
(245, 'Uruguay', 'UY'),
(246, 'Eritrea', 'ER'),
(247, 'Cuba', 'CU'),
(248, 'Saint Helena, Ascension And Tristan Da Cunha', 'SH'),
(249, 'Christmas Island', 'CX'),
(250, 'Ethiopia', 'ET'),
(251, 'British Indian Ocean Territory', 'IO'),
(0, 'Unknown', 'Unknown');